implementing v6 information
pagarme/sdks pull request #13
Opened 2021-12-27 18:08 UTC by magnomoreira

2021-12-29 15:27 UTC, lanz1e requested changes

2021-12-29 15:27 UTC, lanz1e commented on README.md
> +aceitarão mais PRs, porque são geradas automaticamente.
```suggestion
No entanto, ainda não estamos disponibilizando todas as SDKs, pois estão em processo de desenvolvimento. E, Por fim, nossas SDKs não aceitarão mais PRs, já que as mesmas são geradas automaticamente.
```

2021-12-29 15:27 UTC, lanz1e commented on README.md
> +Sdks referente a v5. Aqui pensamos em cada passo para que você tenha uma experiência única e consiga transacionar com poucas linhas de código.
```suggestion
SDKs referente a v5. Aqui pensamos em cada passo para que você tenha uma experiência única e consiga transacionar com poucas linhas de código.
```

2021-12-29 15:27 UTC, lanz1e commented on README.md
>  Através deste repositório, você conseguirá da andamento ao desenvolvimento do seu projeto. Aqui você encontrará exemplos práticos 
```suggestion
Através deste repositório, você conseguirá dar andamento ao desenvolvimento do seu projeto. Aqui você encontrará exemplos práticos sobre a integração com nossas SDKs referente a v6, que trazem correções significativas para clientes que utilizam múltiplas accounts.
```

2021-12-29 15:27 UTC, lanz1e commented on README.md
> +sobre a integração com nossas SDKs referente a v6, que trazem correções significativas para clientes que utilizam múltiplas accounts.
```suggestion
```

2021-12-29 19:38 UTC, samuelleitemundipagg requested changes

2021-12-29 19:38 UTC, samuelleitemundipagg commented on .vs/VSWorkspaceState.json
> +{
remove esse arquivo

2021-12-29 19:38 UTC, samuelleitemundipagg commented on README.md
> +No entanto, ainda não estamos disponibilizando todas as SDKs, pois estão em processo de desenvolvimento. E, Por fim, nossas SDKs não aceitarão mais PRs, já que as mesmas são geradas automaticamente.
retira a letra maiuscula de "Por" na parte "E, Por fim, nossas SDKs...."

2021-12-29 19:38 UTC, samuelleitemundipagg commented on README.md
> +SDKs referente a v5. Aqui pensamos em cada passo para que você tenha uma experiência única e consiga transacionar com poucas linhas de código.
Para facilitar a integração com a v5 disponibilizamos os repositórios abaixo:

2021-12-30 14:38 UTC, lanz1e approved these changes

2021-12-30 16:20 UTC, samuelleitemundipagg approved these changes

2022-01-03 12:07 UTC, merged